### ISSUE TITLE
The autocomplete worked very well last wk. But now it is not both here an my local dev...

### ISSUE THREAD

**Issue by hekevin** [tmentink/jquery.geocomplete#4]

**Comment by tmentink** [comment]
Have you tried opening the developer tools inside your browser and checking the error message? 

The reason it isn't working on the demo page is because I haven't set up a [billing account](https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors) for that API_KEY. You're likely running into a similar issue since the library is still working fine on one of my production websites. 

If you've set up a billing account and are still having issues then check to make sure you have [registered your URLs](https://developers.google.com/maps/documentation/javascript/get-api-key#registering-authorized-urls). Once again, checking the [developer tools](https://developers.google.com/web/tools/chrome-devtools/) will inform you of the issue.
